export const ROUTES = {
  HOME: '/',
  REGISTER_PERSON: '/auth/register-person',
  JOB_POSTING: '/job-posting',
  JOB_LIST: '/jobs',
  JOB_DETAIL: '/jobs/:id',
  REGISTER_BUSINESS: '/auth/register-business',
  ND70: '/nghi-dinh-70',
  CANDIDATE: '/candidate',
  DETAIL_CANDIDATE: '/candidate/:id',
  PROFILE: '/profile',
  ABOUT: '/about',
  INSURANCE: '/inscurance',
  NEWS: '/news',
  LABOREXPORT: '/labor-export',
}
